# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec724a2411c22304492b930e264875303ecd1581c4807557de38cda8427e089d8055ab50d14420969704da09cae90e59e58b10a2c7c0a843dd0b5f61fcf88e76

test:
  secret_key_base: 369454fe21cdae75f764d54d830ca3efb7a2717c72d7f7dc19aabd59dbc9059e43fc762042f82331627863d22fb4adfb38aaf1339ce927a5776b002ccc28c229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
